server:
  port: 8081
spring:
  application:
    name: service-celulares
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
eureka:
  client:
    service-url:
      deafaultZone: https://localhost:8761/eureka 
